src/Entity/PointRelais.php
<?php

namespace App\Entity;

use App\Repository\PointRelaisRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=PointRelaisRepository::class)
 * @ORM\Table(name="point_relais")
 */
class PointRelais
{
     /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id_pt;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;
     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Livraison", mappedBy="pointRelais")
     */
    private $livraisons;
   

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom est obligatoire.")
     * @Assert\Regex(
     *     pattern="/^[a-zA-Z]+$/",
     *     message="Le nom ne doit contenir que des lettres de l'alphabet."
     * )
     */
    #[ORM\Column(length: 255)]
    private ?string $nom_pt = null;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="La ville est obligatoire.")
     * @Assert\Choice(
     * choices={"bizerte", "ariana", "tunis", "sfax"},
     * message="La ville doit être l'une des valeurs suivantes : bizerte, ariana, tunis, sfax."
     * )
     */
    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    public function getId(): ?int
    {
        return $this->id_pt;
    }

    public function getNomPt(): ?string
    {
        return $this->nom_pt;
    }

    public function setNomPt(string $nom_pt): self
    {
        $this->nom_pt = $nom_pt;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function __construct()
    {
        $this->livraisons = new ArrayCollection();
    }

    public function addLivraison(Livraison $livraison): self
    {
        if (!$this->livraisons->contains($livraison)) {
            $this->livraisons[] = $livraison;
            $livraison->setPointRelais($this);
        }

        return $this;
    }
    public function removeLivraison(Livraison $livraison): self
    {
        if ($this->livraisons->contains($livraison)) {
            $this->livraisons->removeElement($livraison);
            // set the owning side to null (unless already changed)
            if ($livraison->getPointRelais() === $this) {
                $livraison->setPointRelais(null);
            }
        }

        return $this;
    }

    public function getIdPt(): ?int
    {
        return $this->id_pt;
    }

    /**
     * @return Collection<int, Livraison>
     */
    public function getLivraisons(): Collection
    {
        return $this->livraisons;
    }

    public function __toString(): string
    {
        return $this->id_pt; // replace with the property you want to use as a string representation
    }
    




}

src/Form/PointRelaisType.php
<?php

namespace App\Form;

use App\Entity\PointRelais;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PointRelaisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_pt')
            ->add('ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PointRelais::class,
        ]);
    }
}

src/Controller/PointRelaisController.php
<?php

namespace App\Controller;

use App\Entity\PointRelais;
use App\Form\PointRelaisType;
use App\Repository\PointRelaisRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;



#[Route('/point/relais')]
class PointRelaisController extends AbstractController
{
    #[Route('/', name: 'app_point_relais_index', methods: ['GET'])]
    public function index(Request $request, PointRelaisRepository $pointRelaisRepository, PaginatorInterface $paginator): Response
    {
        $point_relais = $pointRelaisRepository->findAll();
        $pagination = $paginator->paginate(
            $point_relais,
            $request->query->getInt('page', 1),
            5 //limit par page
        );
    
        return $this->render('point_relais/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }
    


    #[Route('/new', name: 'app_point_relais_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PointRelaisRepository $pointRelaisRepository): Response
    {
        $pointRelai = new PointRelais();
        $form = $this->createForm(PointRelaisType::class, $pointRelai);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pointRelaisRepository->save($pointRelai, true);

            return $this->redirectToRoute('app_point_relais_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('point_relais/new.html.twig', [
            'point_relai' => $pointRelai,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_point_relais_show', methods: ['GET'])]
    public function show(PointRelais $pointRelai): Response
    {
        return $this->render('point_relais/show.html.twig', [
            'point_relai' => $pointRelai,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_point_relais_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PointRelais $pointRelai, PointRelaisRepository $pointRelaisRepository): Response
    {
        $form = $this->createForm(PointRelaisType::class, $pointRelai);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pointRelaisRepository->save($pointRelai, true);

            return $this->redirectToRoute('app_point_relais_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('point_relais/edit.html.twig', [
            'point_relai' => $pointRelai,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_point_relais_delete', methods: ['POST'])]
    public function delete(Request $request, PointRelais $pointRelai, PointRelaisRepository $pointRelaisRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pointRelai->getId(), $request->request->get('_token'))) {
            $pointRelaisRepository->remove($pointRelai, true);
        }

        return $this->redirectToRoute('app_point_relais_index', [], Response::HTTP_SEE_OTHER);
    }

    


public function map(PointRelaisRepository $pointRelaisRepository)
{
    // Get all point relais
    $pointRelaisList = $pointRelaisRepository->findAll();
    
    // Render the map view and pass the list of point relais to it
    return $this->render('map.html.twig', [
        'pointRelaisList' => $pointRelaisList,
    ]);
}



public function myChart(PointRelaisRepository $repository): Response
{
    // Récupérer les données de la base de données
    $data = $repository->getDataForPieChart();

    // Préparer les données pour le graphique
    $pieData = [];
    $pieData[] = ['ville', 'nom'];
    foreach ($data as $row) {
        $pieData[] = [$row['ville'], $row['nom']];
    }

    // Créer le graphique en cercle
    $pieChart = new PieChart();
    $pieChart->getData()->setArrayToDataTable($pieData);
    $pieChart->getOptions()->setTitle('My Pie Chart');
    $pieChart->getOptions()->setHeight(400);
    $pieChart->getOptions()->setWidth(600);

    // Afficher le graphique dans une vue Twig
    return $this->render('chart.html.twig', [
        'pieChart' => $pieChart
    ]);
}









}

templates/point_relais/_delete_form.html.twig
<form method="post" action="{{ path('app_point_relais_delete', {'id': point_relai.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ point_relai.id) }}">
    <button class="btn">Delete</button>
</form>

templates/point_relais/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
     {% include 'map.html.twig' %}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/point_relais/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PointRelais{% endblock %}

{% block body %}
    <h1>Edit PointRelais</h1>

    {{ include('point_relais/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_point_relais_index') }}">back to list</a>

    {{ include('point_relais/_delete_form.html.twig') }}
{% endblock %}

templates/point_relais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PointRelais index{% endblock %}

{% block body %}
    <h1>PointRelais index</h1>
 
 {% include 'map.html.twig' %}

    <button style="background-color: #8B00FF; color: white; padding: 10px 20px; border: none; border-radius: 4px;">
  <a href="{{ path('app_point_relais_new') }}" style="text-decoration: none; color: white;">Create new</a>
</button>

{% endblock %}

templates/point_relais/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PointRelais{% endblock %}

{% block body %}
    <h1>Create new PointRelais</h1>

    {{ form_start(form, {attr:{novalidate:'novalidate'} })  }}

    {{ include('point_relais/_form.html.twig') }}

    <a href="{{ path('app_point_relais_index') }}">back</a>


    
{% endblock %}

templates/point_relais/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PointRelais{% endblock %}

{% block body %}
    <h1>PointRelais</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ point_relai.id }}</td>
            </tr>
            <tr>
                <th>Nom_pt</th>
                <td>{{ point_relai.nomPt }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ point_relai.ville }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_point_relais_index') }}">back to list</a>

    <a href="{{ path('app_point_relais_edit', {'id': point_relai.id}) }}">edit</a>

    {{ include('point_relais/_delete_form.html.twig') }}
{% endblock %}